//
// Asset.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Asset: Identifiable, Codable {
    public var id: UUID = UUID()
    public var assetName: String?
    public var description: String?
    
    public init(assetName: String? = nil, description: String? = nil) {
        self.assetName = assetName
        self.description = description
    }
    
    public enum CodingKeys: String, CodingKey {
        case assetName
        case description = "description"
    }
    
}


var MockAssetList: [Asset] = [Asset(assetName: Optional("sneaker_airforce.usdz"), description: Optional("Sneaker Airforce description")), Asset(assetName: Optional("Resnet50.mlmodel"), description: Optional("Resnet50 ML model description"))]
