//
// Asset.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Asset: Codable {

    public var assetName: Data?
    public var _description: String?

    public init(assetName: Data? = nil, _description: String? = nil) {
        self.assetName = assetName
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case assetName
        case _description = "description"
    }

}
