//
// Confirmation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Confirmation: Codable {

    public var comment: String?
    public var photoUrl: String?
    public var date: Int64?
    /** Whether the step was successfully finished by the user. */
    public var done: Bool?

}
