//
// Confirmation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Confirmation: Codable {

    public var comment: String?
    public var photoUrl: String?
    public var date: Int64?
    /** Whether the step was successfully finished by the user. */
    public var done: Bool
    
    public init(
        comment: String? =  "",
        photoUrl: String? = "",
        date: Int64? = 0,
        done: Bool = false
    ) {
        self.comment = comment
        self.photoUrl = photoUrl
        self.date = date
        self.done = done
    }

}
