//
// Content.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Content: Codable {

    public enum ContentType: String, Codable {
        case image = "image"
        case textblock = "textblock"
    }
    public var contentType: ContentType?
    public var order: Int?
    public var text: String?

}
