//
// ExtendedGuide.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ExtendedGuide: Codable {

    public enum GuideType: String, Codable {
        case manual = "manual"
        case tutorial = "tutorial"
        case wizard = "wizard"
        case witch = "witch"
    }
    public var id: String?
    public var name: String
    public var description: String?
    public var imageUrl: String?
    public var guideType: GuideType
    public var objectSteps: [ObjectStep]?

    public init(id: String? = nil, name: String, description: String? = nil, imageUrl: String? = nil, guideType: GuideType, objectSteps: [ObjectStep]? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.imageUrl = imageUrl
        self.guideType = guideType
        self.objectSteps = objectSteps
    }
    
}
