//
// Guide.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Guide: Identifiable, Codable {

    public enum GuideType: String, Codable {
        case manual = "manual"
        case tutorial = "tutorial"
        case wizard = "wizard"
        case witch = "witch"
    }
    public var id: String?
    public var name: String
    public var description: String?
    public var imageUrl: String?
    public var guideType: GuideType

    public init(id: String? = nil, name: String, description: String? = nil, imageUrl: String? = nil, guideType: GuideType) {
        self.id = id
        self.name = name
        self.description = description
        self.imageUrl = imageUrl
        self.guideType = guideType
    }

}
