//
// Guide.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Guide: Identifiable, Codable {
    
    public enum GuideType: String, Codable {
        case manual = "manual"
        case tutorial = "tutorial"
        case wizard = "wizard"
        case witch = "witch"
    }
    public var id: String?
    public var name: String
    public var _description: String?
    public var imageUrl: String?
    public var guideType: GuideType
    
    public init(_id: String? = nil, name: String, _description: String? = nil, imageUrl: String? = nil, guideType: GuideType) {
        self.id = _id
        self.name = name
        self._description = _description
        self.imageUrl = imageUrl
        self.guideType = guideType
    }
    
    public enum CodingKeys: String, CodingKey {
        case id = "id"
        case name
        case _description = "description"
        case imageUrl
        case guideType
    }
    
}

var MockGuideList: [Guide] = [Guide(_id: Optional("640b700f16cde6145a3bfc19"), name: "Upgrading old Prusa MK2s.", _description: Optional("How to upgrade the old MK2s to MK2s+ featuring the cool magnetic heatbed."), imageUrl: Optional("/images/guides/10/34.png"), guideType: Guide.GuideType.manual), Guide(_id: Optional("640b701216cde6145a3bfc1a"), name: "Upgrading old Prusa MK2s.", _description: Optional("How to upgrade the old MK2s to MK2s+ featuring the cool magnetic heatbed."), imageUrl: Optional("/images/guides/10/34.png"), guideType: Guide.GuideType.manual), Guide(_id: Optional("640b701316cde6145a3bfc1b"), name: "Upgrading old Prusa MK2s.", _description: Optional("How to upgrade the old MK2s to MK2s+ featuring the cool magnetic heatbed."), imageUrl: Optional("/images/guides/10/34.png"), guideType: Guide.GuideType.manual)]
