//
// Instruction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Instruction: Codable {

    public var title: String?
    public var text: String?
    public var imageUrl: String?

}
