//
// ObjectStep.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ObjectStep: Codable {

    public var modelId: Int?
    public var objectName: String?
    public var steps: [Step]?
    public var instruction: Instruction?
    public var order: Decimal?

    public init(modelId: Int? = nil, objectName: String? = nil, steps: [Step]? = nil, instruction: Instruction? = nil, order: Decimal? = nil) {
        self.modelId = modelId
        self.objectName = objectName
        self.steps = steps
        self.instruction = instruction
        self.order = order
    }


}
