//
// Step.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Step: Identifiable, Codable {

    public var id: String
    public var objectName: String?
    public var coordinates: [Coordinates]?
    public var contents: [Content]?
    public var confirmation: Confirmation?
    public var order: Int?

    public init(id: String? = nil, objectName: String? = nil, coordinates: [Coordinates]? = nil, contents: [Content], confirmation: Confirmation? = nil, order: Int? = nil) {
        self.id = id ?? UUID().uuidString
        self.objectName = objectName
        self.coordinates = coordinates
        self.contents = contents
        self.confirmation = confirmation
        self.order = order
    }
    
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decodeIfPresent(String.self, forKey: .id) ?? UUID().uuidString
        objectName = try container.decodeIfPresent(String.self, forKey: .objectName)
        coordinates = try container.decodeIfPresent([Coordinates].self, forKey: .coordinates)
        contents = try container.decodeIfPresent([Content].self, forKey: .contents)
        confirmation = try container.decodeIfPresent(Confirmation.self, forKey: .confirmation)
        order = try container.decodeIfPresent(Int.self, forKey: .order)
    }


}
